#!/bin/bash

#Get the namer of the current folder
folder_name=$(basename "$(pwd)")

echo "This is the Table of Contents of $folder_name Repository: " > TOC.md
for item in *; do
	echo "- $item" >> TOC.md
done
